name = "cloudflare-ai-example"
pages_build_output_dir = "./dist"
#main = "src/index.tsx"

#[site]
#bucket="./dist"

[vars]
AI_CHAT_MODEL_ID="@cf/meta/llama-3-8b-instruct"
AI_EMBEDDINGS_MODEL_ID="@cf/baai/bge-large-en-v1.5"

[ai]
binding="AI"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "rag-example"
database_id = "eb287ca4-3518-46f2-8065-7f0355cd5124"

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "rag-example"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"